In [1]:
import numpy as np

In [26]:
n = 2
x = np.arange(6).reshape((3, 2))

x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
from sklearn.metrics import pairwise_distances
train = x
# distance_matrix = pairwise_distances(train, self._use_correlations)
distance_matrix = pairwise_distances(train.T, metric='correlation')
distance_matrix

array([[0.00000000e+00, 2.22044605e-16],
       [2.22044605e-16, 0.00000000e+00]])

In [29]:
p=1
idx_row, idx_col = np.triu_indices(train.shape[1], k=1)
triu_vals = distance_matrix[idx_row, idx_col]
minimum_distance_pairs_idx = np.argsort(triu_vals)[:p]
minimum_distance_pairs_idx, triu_vals, np.argsort(triu_vals)

(array([0], dtype=int64), array([2.22044605e-16]), array([0], dtype=int64))

In [30]:
_pairs = (idx_row[minimum_distance_pairs_idx],
                       idx_col[minimum_distance_pairs_idx])

In [31]:
_pairs

(array([0]), array([1]))

In [40]:
B = np.zeros((n, p))
B[_pairs[0], np.arange(p)] = 1
B[_pairs[1], np.arange(p)] = -1
B, x @ B, -B @ B.T, -x @ B @ B.T

(array([[ 1.],
        [-1.]]),
 array([[-1.],
        [-1.],
        [-1.]]),
 array([[-1.,  1.],
        [ 1., -1.]]),
 array([[ 1., -1.],
        [ 1., -1.],
        [ 1., -1.]]))

In [25]:
x[:, _pairs[0]] - x[:, _pairs[1]]

array([[-1],
       [-1],
       [-1]])